# Generated by Django 4.1.7 on 2023-04-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fhsapp', '0002_remove_signup_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='location',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='username',
        ),
    ]
