# Generated by Django 4.1.7 on 2023-04-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fhsapp', '0003_remove_signup_location_remove_signup_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
