# Generated by Django 4.1.7 on 2023-05-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhsapp', '0007_manager_restaurants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='category',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='contact',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='cuisine',
            field=models.CharField(choices=[('italian', 'Italian'), ('mexican', 'Mexican'), ('chinese', 'Chinese'), ('indian', 'Indian')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='online_ordering',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='opening_hours',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='reservations',
            field=models.BooleanField(default=False),
        ),
    ]
