# Generated by Django 4.1.7 on 2023-05-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhsapp', '0008_remove_restaurants_category_restaurants_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='registrationtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
