# Generated by Django 4.1.7 on 2023-05-06 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fhsapp', '0010_signup_is_admin_signup_is_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='registrationtime',
        ),
    ]
